#!/bin/sh
set -e

echo "Starting agent installation demo loop..."

# Update and install required tools
apt-get update
apt-get install -y curl openssl ca-certificates

# Mock systemctl so the install script doesn't fail
echo '#!/bin/sh' > /usr/bin/systemctl
chmod +x /usr/bin/systemctl

# Wait for server to be fully ready
echo "Waiting for server to be ready..."
sleep 10

AGENT_NAME=$1
echo "Installing as agent: $AGENT_NAME"

# Download and run the install script
curl -sSL http://server:8080/install.sh | tr -d '\r' | bash -s "$AGENT_NAME"

# Extract the agent run command generated by the script
EXEC_CMD=$(awk -F= '/ExecStart=/ {print $2}' /etc/systemd/system/rmm-agent.service)
echo "Extracted run command: $EXEC_CMD"

# Run the agent in foreground to keep container alive
exec $EXEC_CMD
